# Generated by Django 6.1.1 on 2026-09-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department'),
            preserve_default=False,
        ),
    ]
